[package]
name = "transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.103"
syn = { version = "2.0.108", features = [ "full", "extra-traits" ] }

[[bin]]
path = "src/main.rs"
name = "test"
